name: adtof_rod
channels:
  - defaults
dependencies:
  - python=3.10.20
  - pip
  - pip:
      - tensorflow==2.21.0
      - tf-keras==2.21.0
      - keras==3.12.1
      - numpy==1.26.0
      - scipy==1.15.3
      - pandas==2.3.3
      - matplotlib==3.10.8
      - librosa==0.11.0
      - madmom==0.16.1
      - pretty_midi==0.2.11
      - scikit-learn==1.7.2
      - soundfile==0.13.1
      - mido==1.3.3
      - tqdm
      - jupyter
      - jellyfish==1.0.3
      - mir_eval==0.7
