name: adtof_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow==2.13.0
      - tf-keras
      - typing-extensions==4.5.0
      - numpy
      - scipy
      - matplotlib
      - jupyter
      - madmom
